export const CHANGE_SEARCH_FIELD_RENTAL = 'CHANGE_SEARCH_FIELD_RENTAL';

export const REQUEST_RENTALS_PENDING = 'REQUEST_RENTALS_PENDING';
export const REQUEST_RENTALS_SUCCESS = 'REQUEST_RENTALS_SUCCESS';
export const REQUEST_RENTALS_FAILED = 'REQUEST_RENTALS_FAILED';